### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by jdpedersen1** [mattbutton/silhouette-hugo#12]
Hello,

I am having issues, when i use this theme and preview it with hugo server -D it renders and looks great, but as soon as I build it with hugo -v and upload it, it looks nothing like the previewed version. The image is repeated, the side nav is now on the left below the posts and when open posts the title is half covered up by the header. What am I doing wrong? all I change is the title, and add a post or two. Any help would be appreciated, thanks.

**Comment by mattbutton** [comment]
Heya sorry for the late reply. Guessing you either solved the issue or have moved on.

Guessing you were seeing something like this when using `exampleSite`:

![image](https://user-images.githubusercontent.com/5268841/126768259-efd6b316-9fa0-4391-88c4-706a331cf2ee.png)

For anybody else that sees this, the issue is likely the 'baseUrl' setting in `config.toml` being incorrect, and the web browser being unable to find css/js etc.

By default baseUrl is set to `https://example.com` - this needs to be changed to wherever you're hosting. For example using `serve` https://www.npmjs.com/package/serve , it defaults to hosting locally on `http://localhost:5000`

![image](https://user-images.githubusercontent.com/5268841/126767983-3d74baef-b02d-4973-91e0-8aec8ea51fe8.png)

So I set baseUrl to `http://localhost:5000`:

![image](https://user-images.githubusercontent.com/5268841/126768036-a6ff1266-00b0-4844-925f-2e2846ee61ac.png)

Then rebuilt the `public` folder via `hugo -D`, which regenerates all files within.
